services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
        - PORT=8000
        - DATABASE_URL=postgresql://postgres:test123@mydb:5432/mydb
    depends_on:
      - db    

    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"